version: '3.8'
services:
  app:
    container_name: trent-app    
    build:
      dockerfile: 'Dockerfile.dev'
    depends_on:
      - postgres
    ports:
      - "3030:3030"
    dns:
      - 8.8.8.8
    environment:
      - PORT=3030
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=tasdbuser
      - DB_PASSWORD=pass123456
      - DB_DATABASE=tasdb
      - DB_TYPE=postgres
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
      - JWT_SECRET=Trent_Secret_123
      - JWT_EXPIRES_IN=1d
      - COOKIE_NAME=TrentSecureCookie
    volumes:
      - ./:/app/
  
  postgres:
    container_name: trent-db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=tasdbuser
      - POSTGRES_PASSWORD=pass123456
      - POSTGRES_DB=tasdb
    ports:
      - "5050:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  mailhog:
    container_name: trent-mailhog
    image: mailhog/mailhog
    restart: always
    ports: 
      - "8026:8025"
      - "1026:1025"
